services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    env_file:
      - .env
    environment:
      LANG: ${LANG:-ru}
      WG_HOST: ${WG_HOST}
      PASSWORD_HASH: ${PASSWORD_HASH}
      MAX_AGE: ${MAX_AGE:-15}
      UI_TRAFFIC_STATS: ${UI_TRAFFIC_STATS:-true}
      UI_CHART_TYPE: ${UI_CHART_TYPE:-3}
      WG_ALLOWED_IPS: ${WG_ALLOWED_IPS-0.0.0.0/0}
      WG_PERSISTENT_KEEPALIVE: ${WG_PERSISTENT_KEEPALIVE:-25}
    volumes:
      - ./wireguard:/etc/wireguard
    ports:
      - 51820:51820/udp
      - 51821:51821/tcp
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
